# This is a workflow to deploy a leech bot to heroku using GitHub Actions

name: Deploy To Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.1ea5b10c-4fc9-470b-b8cb-2036f9741405}}
          heroku_app_name: ${{secrets.leechx01bot}}
          heroku_email: ${{secrets.pro963123@gmail.com}}
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "eu"
        env:
          HD_CONFIG_ENV_URL: ${{secrets.https://gist.githubusercontent.com/Forgitunder/8ee29c522bf78d9949b2cbe8df74697e/raw/3e2e15ec2bc490dc598b6d74099992db9b81a1ea/config.env}}
